config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :users do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :taskText, presence: true,
                       length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @task = @user.tasks.create(task_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    @task = @user.tasks.find(params[:id])
    @task.destroy
    redirect_to user_path(@user)
  end

  private
    def task_params
      params.require(:task).permit(:taskText)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Do What You Gotta Do!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Do What You Gotta Do - A Todo App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=http%3A%2F%2Fwww.memes.at%2Ffaces%2Fmeh_cat.jpg"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Do What You Gotta Do by Connie Jew
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "do what you gotta do", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header> -->

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "do what you gotta do", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your Tasks", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1 class="about">What's this all about?</h1>
<p>
  Tired of forgetting to do your chores? Maybe you are sick of constantly
  forgetting what that one important thing you had to do was.
</p>

<p>
  With this app, never will your significant other berate you again for forgetting to pick up the groceries.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1 class="contact">Contact</h1>
<p>
  If you have any questions, you can find me at connie.jew@gmail.com.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1 class="home">Do What You Gotta Do</h1>
  <h2>
    A todo list application to suit your every need
  </h2>

  <%= link_to "Get started!", login_path, class: "btn btn-lg btn-primary" %>
</div>

<div class="image-source">
  <%= image_tag("dowork.jpeg", alt: "do-what-you-gotta-do") %>
  <small>
    <a href="http://lukeroberts.deviantart.com/art/You-Gotta-Do-What-You-Gotta-Do-14827867">Via</a>
  </small>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="signup">Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h3>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h3>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">What's New To Do</h3>
  </div>
  <div class="panel-body">
    <p>Use this section to keep track of your tasks!</p>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h4>Add a task:</h4>
        <%= form_for([@user, Task.new]) do |f| %>
          <p>
            <%= f.label :Task %><br>
            <%= f.text_field :taskText %>
          </p>
          <p>
            <%= f.submit "Submit", class: "task-submit btn btn-primary" %>
          </p>
        <% end %>
      </div>
    </div>

    <h3>What You Gotta Do</h3>

    <ul class="list-group">
      <% if @user.tasks.exists? %>
      <% @user.tasks.each do |task| %>
        <li class="list-group-item">
          <strong>Task:</strong>
          <%= task.taskText %>

          <%= link_to 'Destroy Task', [task.user, task],
                       method: :delete,
                       class: "btn btn-primary btn-xs destroy-button",
                       data: { confirm: 'Did you actually do that?' } %>
        </li>
      <% end %>

      <% else %>
        Do you need to start something? :D
      <% end %>
    </ul>


  </div>
</div>